import React from "react";

const Context =  React.createContext({
    token: "",
    setToken: () => {},
    api:"",
    showModal: false,
    setShowModal: () => {},
    chapterDishesText: [],
    recipes: [],
    idRecipe: "",
    dataRecipe: [],
    setDataRecipe: () => {},
    setRecipes: () => {},
    setIdRecipe: () => {},
    comment: [], 
    setComment: () => {},
    secondMealText: [],
    bakeryText: [],
    userId: "",
    setUserId: () => {},
    favourite: [], 
    setFavourite: () => {},
    flagLike: false,
    setFlagLike: () => {},
    searchText: "", 
    setSearchText: () => {},
    search: [], 
    setSearch: () => {},
    recentRecipe: [], 
    setRecentRecipe: () => {},
    titleChapter: [], 
    setTitleChapter: () => {},
    flagActiv: false, 
    setFlagActiv: () => {},
    apiDefault: "", 
    userToken: "", 
    setUserToken: () => {},
    apiUser: "", 
    userName: "", 
    setUserName: () => {},
    serving: [], 
    setServing: () => {},
    widthScreen: 3, 
    setWidthScreen: () => {}
})
export default Context;